name: example
description: An example Flutter project to demonstrate the usage of cached_build_runner.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  json_serializable: ^6.9.3
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  auto_route: ^9.3.0
  # due to conflict with json_serializable that uses source_gen ^2.0.0
  auto_mappr_annotation:
    git:
      url: https://github.com/amrgetment/auto_mappr.git
      ref: main
      path: packages/auto_mappr_annotation
  flutter_bloc: ^9.0.0

dev_dependencies:
  build_runner: ^2.4.14
  cached_build_runner:
    path: ../
  # due to conflict with json_serializable that uses source_gen ^2.0.0
  auto_mappr:
    git:
      url: https://github.com/amrgetment/auto_mappr.git
      ref: main
      path: packages/auto_mappr

  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  auto_route_generator: ^9.0.0

dependency_overrides:
  # due to conflict with json_serializable that uses source_gen ^2.0.0
  auto_mappr_annotation:
    git:
      url: https://github.com/amrgetment/auto_mappr.git
      ref: main
      path: packages/auto_mappr_annotation

flutter:
  uses-material-design: true
